---
- name: Add key for Mesosphere repository for Debian systems
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add mesosphere repo
  apt_repository: repo='deb http://repos.mesosphere.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} main' state=present update_cache=yes

- name: Install mesos package in Debian
  apt: name=mesos,network-manager state=present update_cache=yes
