---
- name: Copy 'is_cluster_ready' file
  copy: dest=/bin/is_cluster_ready src=is_cluster_ready mode=0755

# Manage the /etc/hosts file
- name: Edit /etc/hosts file
  shell: |
    for i in `seq 1 {{max_number_of_nodes}}`; do
      item="{{vnode_prefix}}${i}";
      grep -q "\<${item}\>" /etc/hosts || echo "127.0.0.1 ${item} ${item}.localdomain" >> /etc/hosts;
    done

- name: Set ZooKeeper URL # used for leader election amongst masters
  copy:
    content: "zk://{{mesos_front_private_ip}}:2181/mesos"
    dest: /etc/mesos/zk
    mode: 0644

- name: Stop and disable the Mesos Slave service
  service: name=mesos-slave state=stopped enabled=no 

# - name: start up zookeeper in Centos 7
#   service: name=zookeeper state=started enabled=yes

- name: Set Mesos Master hostname
  copy:
    content: "{{mesos_front_private_ip}}"
    dest: /etc/mesos-master/hostname
    mode: 0644

- name: Set Mesos framework authentication (frameworks)
  copy:
    content: "true"
    dest: /etc/mesos-master/authenticate_frameworks
    mode: 0600

- name: Set Mesos framework authentication (credentials)
  copy:
    content: "/usr/etc/mesos/credentials"
    dest: /etc/mesos-master/credentials
    mode: 0600

- name: Set Mesos security keys
  copy:
    content: '{"credentials":[ {"principal": "{{principal}}", "secret": "{{secret}}" } ] }'
    dest: /usr/etc/mesos/credentials
    mode: 0600

# Tambien se puede configurar la ip del master con (export MESOS_IP=158.42.104.229)
- name: Set Mesos Master ip (debian)
  copy:
    content: "{{mesos_front_private_ip}}"
    dest: /etc/mesos-master/ip
    mode: 0644

- name: Set Mesos Master quorum count
  copy:
    content: "{{quorum}}"
    dest: /etc/mesos-master/quorum
    mode: 0644

- name: start up the mesos-master in Deb systems
  service: name=mesos-master state=started enabled=yes

- name: Include DNS configuration
  include_tasks: "dns.yml"
  when: mesos_dns_enable | bool
