---
- name: Copy 'is_cluster_ready' file
  copy: dest=/bin/is_cluster_ready src=is_cluster_ready mode=0755

# Manage the /etc/hosts file
- name: Edit /etc/hosts file
  shell: |
    for i in `seq 1 {{max_number_of_nodes}}`; do
      item="{{vnode_prefix}}${i}";
      grep -q "\<${item}\>" /etc/hosts || echo "127.0.0.1 ${item} ${item}.localdomain" >> /etc/hosts;
    done

- name: Set ZooKeeper URL # used for leader election amongst masters
  copy:
    content: "zk://{{ansible_default_ipv4.address}}:2181/mesos"
    dest: /etc/mesos/zk
    mode: 0644

- block:
  - name: start up zookeeper in Centos 6
    command: /usr/lib/zookeeper/bin/zkServer.sh start
    when: ansible_distribution_major_version == "6"

  - block:
    - name: start up zookeeper in Centos 7
      service: name=zookeeper state=started enabled=yes

    # Disable mesos-slave in Redhat
    - name: Stop the Mesos Slave service
      command: systemctl stop mesos-slave.service

    - name: Disable the Mesos Slave service
      command: systemctl disable mesos-slave.service

    when: ansible_distribution_major_version == "7"

  when: ansible_os_family == "RedHat"

- block:
  - name: start up zookeeper in Deb systems
    service: name=zookeeper state=started enabled=yes

  # Master tasks
  - name: Stop the Mesos Slave service
    service: name=mesos-slave state=stopped

  - name: Disable the Mesos Slave service
    copy:
      content: "manual"
      dest: /etc/init/mesos-slave.override
      mode: 0644

  when: ansible_os_family == "Debian"

  - name: Set Mesos Master hostname
    copy:
      content: "{{ansible_hostname}}"
      dest: /etc/mesos-master/hostname
      mode: 0644

  - block:
    - name: Set Mesos framework authentication (frameworks)
      copy:
        content: "true"
        dest: /etc/mesos-master/authenticate_frameworks
        mode: 0600

    - name: Set Mesos framework authentication (credentials)
      copy:
        content: "/usr/etc/mesos/credentials"
        dest: /etc/mesos-master/credentials
        mode: 0600

    - name: Set Mesos security keys
      copy:
        content: '{"credentials":[ {"principal": "{{principal}}", "secret": "{{secret}}" } ] }'
        dest: /usr/etc/mesos/credentials
        mode: 0600

    tags:
      - authentication

# Tambien se puede configurar la ip del master con (export MESOS_IP=158.42.104.229)
- name: Set Mesos Master ip (debian)
  copy:
    content: "{{ansible_default_ipv4.address}}"
    dest: /etc/mesos-master/ip
    mode: 0644

- name: Set Mesos Master quorum count
  copy:
    content: "{{QUORUM}}"
    dest: /etc/mesos-master/quorum
    mode: 0644

- name: start up the mesos-master in Deb systems
  service: name=mesos-master state=started enabled=yes
  when: ansible_os_family == "Debian"

- name: start up the mesos-master in Centos 7
  service: name=mesos-master state=started enabled=yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: start up the mesos-master in Centos 6
  command: start mesos-master
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- file: path=/etc/clues2/ state=directory
- copy:
    content: |
       {% for number in range(1, NNODES|int + 1) %}
       {{vnode_prefix}}{{number}}
       {% endfor %}
    dest: "/etc/clues2/mesos_vnodes.info"
