---
    - name: Add key for Mesosphere repository for RedHat 7 systems
      command: rpm -Uvh http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm creates=/usr/bin/mesos
      when: ansible_os_family == "RedHat"

    - name: Add key for Mesosphere repository for Debian systems
      apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xE56151BF state=present
      when: ansible_os_family == "Debian"
 
    - name: Determine Linux distribution distributor
      shell: lsb_release -is | tr '[:upper:]' '[:lower:]'
      register: release_distributor
      when: ansible_os_family == "Debian"
 
    - name: Determine Linux distribution codename
      command: lsb_release -cs
      register: release_codename
      when: ansible_os_family == "Debian"
 
    - name: Add Mesosphere repository to sources list
      copy:
        content: "deb http://repos.mesosphere.io/{{release_distributor.stdout}} {{release_codename.stdout}} main"
        dest: /etc/apt/sources.list.d/mesosphere.list
        mode: 0644
      when: ansible_os_family == "Debian"

    - name: Install mesos package in Debian
      apt: pkg=mesos state=present update_cache=yes
      when: ansible_os_family == "Debian"

    - name: Install mesos package in RedHat 7
      yum: name=mesos,mesosphere-zookeeper,wget update_cache=yes
      when: ansible_os_family == "RedHat"

    - name: configure containerizers
      shell: echo 'docker,mesos' | sudo tee /etc/mesos-slave/containerizers
      when: "'docker' in TEMPLATES"
    - shell: echo '5mins' | sudo tee /etc/mesos-slave/executor_registration_timeout
      when: "'docker' in TEMPLATES"

    - name: create log directory  
      file:
        path: "{{ mesos_log_dir }}"
        state: directory
        mode: 0755
        tags:
          - mesos-master
          - mesos-slave

    - include: master.yml
      when: mesos_install_mode == "master"

    - include: slave.yml
      when: mesos_install_mode == "slave"
