- name: create log directory  
  file:
    path: "{{ mesos_log_dir }}"
    state: directory
    mode: 0755

- include_tasks: master.yml
  when: mesos_type_of_node == "master"

- include_tasks: slave.yml
  when: mesos_type_of_node == "slave"