---
- name: Include "{{ansible_os_family}}" mesos recipe
  include: "{{ansible_os_family}}.yml"

- name: Configure containerizers
  shell: echo 'docker,mesos' | sudo tee /etc/mesos-slave/containerizers

- name: Configure executor registration timeout
  shell: echo '5mins' | sudo tee /etc/mesos-slave/executor_registration_timeout

- name: create log directory
  file:
    path: "{{ mesos_log_dir }}"
    state: directory
    mode: 0755

- name: Include "{{mesos_type_of_node}}" mesos recipe
  include: "{{mesos_type_of_node}}.yml"

- name: Include CNI configuration
  include: "cni.yml"
