---
- name: Copy zk file from the frontend
  copy: 
    src: "/etc/mesos/zk"
    dest: "/etc/mesos/zk"

- name: Include DNS configuration
  include_tasks: "dns.yml"
  when: mesos_dns_enable | bool

- name: Stop Zookeeer and Mesos master services
  service: 
    name: "{{ item.name }}"
    state: stopped
    enabled: false
  with_items:
    - name: "zookeeper"
    - name: "mesos-master"

- name: Set Mesos Slave configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0664"
  with_items:
    - src: "mesos-slave/ip.j2"
      dest: "/etc/mesos-slave/ip"
    - src: "mesos-slave/hostname.j2"
      dest: "/etc/mesos-slave/hostname"
    - src: "mesos-slave/resources.j2"
      dest: "/etc/mesos-slave/resources"
    - src: "mesos-slave/executor_registration_timeout.j2"
      dest: "/etc/mesos-slave/executor_registration_timeout"
  notify:
    - start mesos-slave