---
    - name: Obtain slave IP in Debian
      shell: ifconfig eth0 | sed -n '/inet addr/s/.*addr.\([^ ]*\) .*/\1/p'
      register: slave_ip_deb
      when: ansible_os_family == "Debian"

    - name: Obtain slave IP in Redhat
      shell: ifconfig ens3 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'
      register: slave_ip_rht
      when: ansible_os_family == "RedHat"

    - name: Obtain slave nodename
      shell: hostname | cut -d "." -f 1
      register: slave_hostname

    - name: Stop zookeeper in wns (debian)
      service: name=zookeeper state=stopped
      when: ansible_os_family == "Debian"

    - name: Disable the ZooKeeper service (debian)
      copy:
        content: "manual"
        dest: /etc/init/zookeeper.override
        mode: 0644
      when: ansible_os_family == "Debian"

    # Disable zookeeper in Redhat
    - name: Stop zookeeper in wns (redhat)
      command: systemctl stop zookeeper.service
      when: ansible_os_family == "RedHat"

    - name: Disable the ZooKeeper service (redhat)
      command: systemctl disable zookeeper.service
      when: ansible_os_family == "RedHat"

    - name: copy zk file from the frontend
      copy: src=/etc/mesos/zk dest=/etc/mesos/zk

    - name: Stop mesos master in wns (debian)
      service: name=mesos-master state=stopped
      when: ansible_os_family == "Debian"

    - name: Disable mesos master in wns (debian)
      copy:
        content: "manual"
        dest: /etc/init/mesos-master.override
        mode: 0644
      when: ansible_os_family == "Debian"

    # Disable mesos-master in Redhat
    - name: Stop mesos master in wns (redhat)
      command: systemctl stop mesos-master.service
      when: ansible_os_family == "RedHat"

    - name: Disable mesos master in wns (redhat)
      command: systemctl disable mesos-master.service
      when: ansible_os_family == "RedHat"

    - name: Set Mesos Slave hostname
      copy:
        content: "{{slave_hostname.stdout}}"
        dest: /etc/mesos-slave/hostname
        mode: 0644

    - name: Set Mesos Slave ip (debian)
      copy:
        content: "{{slave_ip_deb.stdout}}"
        dest: /etc/mesos-slave/ip
        mode: 0644
      when: ansible_os_family == "Debian"

    - name: Set Mesos Slave ip (redhat)
      copy:
        content: "{{slave_ip_rht.stdout}}"
        dest: /etc/mesos-slave/ip
        mode: 0644
      when: ansible_os_family == "RedHat"

    - name: start up the mesos-slave
      service: name=mesos-slave state=started

