---
    - name: Obtain slave nodename
      shell: hostname | cut -d "." -f 1
      register: slave_hostname

    - name: Stop zookeeper in wns (debian)
      service: name=zookeeper state=stopped
      when: ansible_os_family == "Debian"

    - name: Disable the ZooKeeper service (debian)
      copy:
        content: "manual"
        dest: /etc/init/zookeeper.override
        mode: 0644
      when: ansible_os_family == "Debian"

    # Disable zookeeper in Redhat
    - name: Stop zookeeper in wns (redhat 7)
      command: systemctl stop zookeeper.service
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: Disable the ZooKeeper service (redhat 7)
      command: systemctl disable zookeeper.service
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: copy zk file from the frontend
      copy: src=/etc/mesos/zk dest=/etc/mesos/zk

    - name: Stop mesos master in wns (debian)
      service: name=mesos-master state=stopped
      when: ansible_os_family == "Debian"

    - name: Disable mesos master in wns (debian)
      copy:
        content: "manual"
        dest: /etc/init/mesos-master.override
        mode: 0644
      when: ansible_os_family == "Debian"

    # Disable mesos-master in Redhat
    - name: Stop mesos master in wns (redhat 7)
      command: systemctl stop mesos-master.service
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: Disable mesos master in wns (redhat 7)
      command: systemctl disable mesos-master.service
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: Set Mesos Slave hostname
      copy:
        content: "{{slave_hostname.stdout}}"
        dest: /etc/mesos-slave/hostname
        mode: 0644

    - name: Set Mesos Slave ip
      copy:
        content: "{{ansible_default_ipv4.address}}"
        dest: /etc/mesos-slave/ip
        mode: 0644

    - name: start up the mesos-slave in Centos 7
      service: name=mesos-slave state=started
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
      
    - name: start up the mesos-slave in Deb systems
      service: name=mesos-slave state=started
      when: ansible_os_family == "Debian"
  
    - name: start up the mesos-slave in Centos 6
      command: start mesos-slave 
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

