---
- name: Modify permissions zk directory
  file:
    path: "/etc/mesos/zk"
    mode: 0757

- name: Copy zk file from the frontend
  fetch: 
    src: "/etc/mesos/zk"
    dest: "/etc/mesos/zk"
    flat: yes
  delegate_to: '{{IM_MASTER_HOSTNAME}}'

- name: Stop and disable Zookeeer and Mesos master (Debian)
  block:
    - name: Stop Zookeeer and Mesos master services
      service: 
        name: "{{ item.name }}"
        state: stopped
      with_items:
        - name: "zookeeper"
        - name: "mesos-master"

    - name: Disable Zookeeer and Mesos master services
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0664"        
      with_items:
        - src: "mesos-slave/disable_service.override.j2"
          dest: "/etc/init/zookeeper.override"
        - src: "mesos-slave/disable_service.override.j2"
          dest: "/etc/init/mesos-master.override"
  when: ansible_os_family == "Debian"

- name: Stop and disable Zookeeer and Mesos master (CentOS 7)
  command: "{{ item.command }}"
  with_items:
    - command: "systemctl stop zookeeper-server"
    - command: "systemctl stop mesos-master.service"
    - command: "systemctl disable zookeeper-server"
    - command: "systemctl disable mesos-master.service"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Set Mesos Slave configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0664"
  with_items:
    - src: "mesos-slave/ip.j2"
      dest: "/etc/mesos-slave/ip"
    - src: "mesos-slave/hostname.j2"
      dest: "/etc/mesos-slave/hostname"
    - src: "mesos-slave/resources.j2"
      dest: "/etc/mesos-slave/resources"
    - src: "mesos-slave/executor_registration_timeout.j2"
      dest: "/etc/mesos-slave/executor_registration_timeout"
    - src: "mesos-slave/docker_remove_delay.j2"
      dest: "/etc/mesos-slave/docker_remove_delay"
    - src: "mesos-slave/enforce_container_disk_quota.j2"
      dest: "/etc/mesos-slave/enforce_container_disk_quota"
  notify:
    - start mesos-slave
