---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

  - apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_distribution == "Ubuntu"
  
  - copy:
      content: "NETWORKING=yes"
      dest: /etc/sysconfig/network
    when: ansible_os_family == "RedHat"

  tasks:

    - name: "Test grycap.mesos front"
      include_role:
        name: "ansible-role-mesos"
      vars:
        mesos_type_of_node: "master"
        mesos_front_private_ip: "127.0.0.1"

    - name: "Test grycap.mesos wn"
      include_role:
        name: "ansible-role-mesos"
      vars:
        mesos_type_of_node: "slave"
        mesos_front_private_ip: "127.0.0.1"