---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

  - apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_distribution == "Ubuntu"

  tasks:

    - name: "Test grycap.mesos front"
      include_role:
        name: "ansible-role-mesos"
      vars:
        mesos_type_of_node: "front"
        mesos_ssh_user: ""


    - name: "Test grycap.mesos wn"
      include_role:
        name: "ansible-role-mesos"
      vars:
        mesos_type_of_node: "wn"
        mesos_front_private_ip: "127.0.0.1"
        mesos_ssh_user: ""