---
name: CI

on:

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install python
        run: sudo apt update && sudo apt install -y python3 python3-pip python3-setuptools
    
      - name: Remove pre-installed kubectl to avoid errors
        run: sudo apt remove buildah podman kubectl containers-image containers-common -y

      - name: Install Ansible
        run: sudo pip3 install ansible

      - name: Create ansible.cfg with correct roles_path
        run: sudo printf '[defaults]\nhost_key_checking = False\nroles_path=../' > ansible.cfg
  
      - name: Install geerlingguy.ntp
        run: sudo ansible-galaxy install geerlingguy.ntp

      - name: Install grycap.docker
        run: sudo ansible-galaxy install grycap.docker

      - name: Install grycap.zookeeper
        run: sudo ansible-galaxy install grycap.zookeeper

      - name: Basic role syntax check
        run: sudo ansible-playbook tests/test.yml -i tests/inventory --syntax-check

      - name: Basic role check in front
        run: sudo ansible-playbook tests/test.yml -i tests/inventory

      - name: Basic role check in wn
        run: sudo ansible-playbook tests/test.yml -i tests/inventory -e mesos_type_of_node=wn
